/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PasswordManager;

import java.awt.Color;



/**
 *
 * @author Sebastián
 */
public class Registro extends javax.swing.JFrame {
     
     

    /**
     * Creates new form Registro
     */
    public Registro() {
        
        initComponents();
        btn_registro.setBackground(new Color(102,102,255));
        btn_registro.setForeground(Color.white);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        label_registrate.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_registrate = new javax.swing.JLabel();
        btn_registro = new javax.swing.JButton();
        lb_password = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        textfield_nombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        fondo_cerrar = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        fondo_minimizar = new javax.swing.JPanel();
        minimizar = new javax.swing.JLabel();
        lb_inicio = new javax.swing.JLabel();
        lb_nombre = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textfield_pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_registrate.setFont(new java.awt.Font("Roboto Light", 0, 50)); // NOI18N
        label_registrate.setForeground(new java.awt.Color(102, 102, 255));
        label_registrate.setText("Registrate");
        jPanel1.add(label_registrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 230, 69));

        btn_registro.setBackground(new java.awt.Color(255, 255, 255));
        btn_registro.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        btn_registro.setText("Aceptar");
        btn_registro.setBorder(null);
        btn_registro.setFocusPainted(false);
        btn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registroActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 120, 40));

        lb_password.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        lb_password.setForeground(new java.awt.Color(255, 255, 255));
        lb_password.setText("Contraseña");
        jPanel1.add(lb_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 80, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 290, -1));

        textfield_nombre.setBackground(new java.awt.Color(51, 51, 51));
        textfield_nombre.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        textfield_nombre.setForeground(new java.awt.Color(255, 255, 255));
        textfield_nombre.setBorder(null);
        textfield_nombre.setCaretColor(new java.awt.Color(255, 255, 255));
        textfield_nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textfield_nombre.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        textfield_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfield_nombreMouseClicked(evt);
            }
        });
        jPanel1.add(textfield_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 290, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 290, -1));

        fondo_cerrar.setBackground(new java.awt.Color(102, 102, 255));
        fondo_cerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });
        fondo_cerrar.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 40));

        jPanel1.add(fondo_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 40));

        fondo_minimizar.setBackground(new java.awt.Color(102, 102, 255));
        fondo_minimizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizar.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        minimizar.setForeground(new java.awt.Color(255, 255, 255));
        minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizar.setText("-");
        minimizar.setAlignmentX(0.5F);
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizarMouseExited(evt);
            }
        });
        fondo_minimizar.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 40));

        jPanel1.add(fondo_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, 40));

        lb_inicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lb_inicio.setForeground(new java.awt.Color(255, 255, 255));
        lb_inicio.setText(" Volver a Inicio de Sesion");
        lb_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_inicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_inicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_inicioMouseExited(evt);
            }
        });
        jPanel1.add(lb_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 160, 30));

        lb_nombre.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        lb_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lb_nombre.setText("Nombre de usuario");
        jPanel1.add(lb_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 130, 30));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 40));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password Manager");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 120, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 40));

        textfield_pass.setBackground(new java.awt.Color(51, 51, 51));
        textfield_pass.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        textfield_pass.setForeground(new java.awt.Color(255, 255, 255));
        textfield_pass.setBorder(null);
        textfield_pass.setCaretColor(new java.awt.Color(255, 255, 255));
        textfield_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfield_passMouseClicked(evt);
            }
        });
        jPanel1.add(textfield_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registroActionPerformed
        boolean verificacion;
        String registro_nombre,registro_password;


        
        registro_nombre = textfield_nombre.getText().trim();
        registro_password = textfield_pass.getText().trim();

        
        if("".equals(registro_nombre)){
            Main.Mensaje("El campo 'Nombre' esta vacio.","Advertencia","");
        }
        else if ("".equals(registro_password)){
            Main.Mensaje("El campo 'Contraseña' esta vacio.","Advertencia","");
        }else{
            verificacion = Conexion.ValidarRegistro(registro_nombre);
            if (verificacion == true) {
               Main.Mensaje("El usuario ya se encuentra registrado.","Error","Error");
            }else{
               Conexion.Registrar(registro_nombre, registro_password);
               Main.Mensaje("El usuario se creo correctamente.","","correcto");
            }
        }    
        
    }//GEN-LAST:event_btn_registroActionPerformed

  
    
    
    
    
    private void textfield_nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfield_nombreMouseClicked
        jSeparator2.setBackground(new Color(102,102,255));
        jSeparator1.setBackground(Color.white);
    }//GEN-LAST:event_textfield_nombreMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        fondo_cerrar.setBackground(Color.decode("#5555fd"));
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        fondo_cerrar.setBackground(Color.decode("#6666ff"));
    }//GEN-LAST:event_cerrarMouseExited

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void minimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseEntered
        fondo_minimizar.setBackground(Color.decode("#5555fd"));
    }//GEN-LAST:event_minimizarMouseEntered

    private void minimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseExited
        fondo_minimizar.setBackground(Color.decode("#6666ff"));
    }//GEN-LAST:event_minimizarMouseExited

    private void lb_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_inicioMouseClicked
        this.dispose();
        Login login = new Login();
    }//GEN-LAST:event_lb_inicioMouseClicked

    private void lb_inicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_inicioMouseEntered
        lb_inicio.setForeground(new Color(102,102,255)); 
    }//GEN-LAST:event_lb_inicioMouseEntered

    private void lb_inicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_inicioMouseExited
        lb_inicio.setForeground(Color.decode("#ffffff"));
    }//GEN-LAST:event_lb_inicioMouseExited

    private void textfield_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfield_passMouseClicked
        jSeparator1.setBackground(new Color(102,102,255));
        jSeparator2.setBackground(Color.white);
    }//GEN-LAST:event_textfield_passMouseClicked

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registro;
    private javax.swing.JLabel cerrar;
    private javax.swing.JPanel fondo_cerrar;
    private javax.swing.JPanel fondo_minimizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_registrate;
    private javax.swing.JLabel lb_inicio;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel minimizar;
    private javax.swing.JTextField textfield_nombre;
    private javax.swing.JPasswordField textfield_pass;
    // End of variables declaration//GEN-END:variables
}
